
version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      day: "friday"
    open-pull-requests-limit: 4
