name: Java CI

on: [push, pull_request]

jobs:
  build_legacy:
    name: Test with old Java ${{ matrix.jdk }}
    runs-on: ubuntu-16.04 # for older version of Ant
    strategy:
      fail-fast: false
      matrix:
        jdk: ['6', '7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Ant
      run: ant -noinput -buildfile barcode4j/build.xml

  build_modern:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '9', '10', '11', '12', '13', '14-ea', '15-ea']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Ant
      run: ant -noinput -buildfile barcode4j/build.xml
