name: Ant

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17']
        # Will need to target JDK 7 as minimum in order to build with Java: '12', '13', '14-ea', '15-ea'

    steps:
    - uses: actions/checkout@v4

    - name: Install Junit 5
      run: sudo apt-get install ant ant-optional junit5 -y

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}

    - name: Build with Ant
      run: ant -noinput -buildfile barcode4j/build.xml

    - name: Build Distribution
      run: ant -noinput -buildfile barcode4j/build-dist.xml
