name: Ant

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17']
        # Will need to target JDK 7 as minimum in order to build with Java: '12', '13', '14-ea', '15-ea'

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Ant
      run: ant -noinput -buildfile barcode4j/build.xml

    - name: Build Distribution
      run: ant -noinput -buildfile barcode4j/build-dist.xml
