name: Maven

on: [push, pull_request]

jobs:

  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['7', '8', '11', '17']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
