name: Maven

on: [push, pull_request]

jobs:

  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '20']

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    name: Deploy Artifact
    needs: build
    if: ${{ needs.build.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          # JDK 11 is used for release so that multi-release jar is possible
          distribution: temurin
          java-version: 8
          cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase


      - name: Maven Deploy
        run: mvn deploy -Pgithub -Prelease -DskipTests=true
        env:
          MAVEN_USERNAME: 'SingingBush'
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN  }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
